spring:
  datasource:
    url: jdbc:sqlserver://${HOST_SQL}:${DB_PORT};databaseName=${DB_NAME};encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update